# Generated by Django 5.1.2 on 2024-11-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='название компании')),
                ('codephrase', models.CharField(max_length=10, verbose_name='кодовая фраза')),
            ],
            options={
                'verbose_name': 'кодовая фраза',
                'verbose_name_plural': 'кодовые фразы',
            },
        ),
    ]
