# Generated by Django 5.1.2 on 2024-10-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='номер дома'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='улица'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
