# Generated by Django 5.1.2 on 2024-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_city_supplier_country_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='задолженность'),
        ),
    ]
